services:
  app:
    image: node:24
    container_name: biblioteca-virtual-front
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true

  api:
    image: clue/json-server
    container_name: biblioteca-virtual-api
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json